// Builds the static UI for GitHub Pages into docs/ (Settings → Pages →
// deploy from branch, /docs folder). The UI talks to the Supabase edge
// function cross-origin, so config.js points at its URL here.
import fs from 'fs';
import path from 'path';

const API_BASE = 'https://ocovjbvrtbxptqtucyqw.supabase.co/functions/v1/btc-tracker/';

const root = path.join(import.meta.dirname, '..');
const out = path.join(root, 'docs');
fs.mkdirSync(out, { recursive: true });

for (const file of ['index.html', 'app.js', 'style.css', 'login.html', 'manifest.webmanifest']) {
  fs.copyFileSync(path.join(root, 'public', file), path.join(out, file));
}
fs.mkdirSync(path.join(out, 'icons'), { recursive: true });
for (const icon of fs.readdirSync(path.join(root, 'public', 'icons'))) {
  fs.copyFileSync(path.join(root, 'public', 'icons', icon), path.join(out, 'icons', icon));
}
fs.writeFileSync(
  path.join(out, 'config.js'),
  `// Generated by scripts/build-pages.mjs — points the static UI at the API.\nwindow.BTC_API_BASE = ${JSON.stringify(API_BASE)};\n`
);
fs.writeFileSync(path.join(out, '.nojekyll'), '');
console.log('GitHub Pages bundle written to docs/');
