// Builds the static UI for GitHub Pages into docs/ (Settings → Pages →
// deploy from branch, /docs folder). The UI talks to the Supabase edge
// function cross-origin, so config.js points at its URL here.
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const API_BASE = 'https://ocovjbvrtbxptqtucyqw.supabase.co/functions/v1/btc-tracker/';

const root = path.join(import.meta.dirname, '..');
const out = path.join(root, 'docs');
fs.mkdirSync(out, { recursive: true });

for (const file of ['index.html', 'app.js', 'style.css', 'login.html', 'manifest.webmanifest']) {
  fs.copyFileSync(path.join(root, 'public', file), path.join(out, file));
}
fs.mkdirSync(path.join(out, 'icons'), { recursive: true });
for (const icon of fs.readdirSync(path.join(root, 'public', 'icons'))) {
  fs.copyFileSync(path.join(root, 'public', 'icons', icon), path.join(out, 'icons', icon));
}
fs.writeFileSync(
  path.join(out, 'config.js'),
  `// Generated by scripts/build-pages.mjs — points the static UI at the API.\nwindow.BTC_API_BASE = ${JSON.stringify(API_BASE)};\n`
);
fs.writeFileSync(path.join(out, '.nojekyll'), '');

// Cache-busting: GitHub Pages serves everything with max-age=600, so stamp
// asset references with a content hash — a new deploy shows up as soon as
// the HTML itself refreshes instead of waiting out a second cache layer.
const hash = (file) =>
  crypto.createHash('sha1').update(fs.readFileSync(path.join(out, file))).digest('hex').slice(0, 8);
const versions = { 'app.js': hash('app.js'), 'style.css': hash('style.css'), 'config.js': hash('config.js') };
for (const page of ['index.html', 'login.html']) {
  const p = path.join(out, page);
  let html = fs.readFileSync(p, 'utf8');
  for (const [file, v] of Object.entries(versions)) {
    html = html.replaceAll(`"${file}"`, `"${file}?v=${v}"`);
  }
  fs.writeFileSync(p, html);
}
console.log('GitHub Pages bundle written to docs/');
